name: .NET Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./src/DiscordFakeGameLauncher/DiscordFakeGameLauncher.csproj

      - name: Build
        run: dotnet build ./src/DiscordFakeGameLauncher/DiscordFakeGameLauncher.csproj --configuration Release --no-restore
